---
tasks:
  - name: Gitpod config (browser open, workspace bin path)
    init: |
      mkdir -p /workspace/bin
      cat > /workspace/bin/open.sh <<'EOF'
      #!/bin/bash
      exec gp preview --external "$@"
      EOF
      chmod +x /workspace/bin/open.sh
    command: |
      sudo update-alternatives --install /usr/bin/www-browser www-browser /workspace/bin/open.sh 100
      exit
  - name: Pull images
    init: |
      docker compose pull
      gp sync-done pull
  - name: Install python dependencies
    command: |
      pip3 install -r requirements.txt
      python -m venv .venv
      source .venv/bin/activate
      pip3 install -r requirements.txt
  - name: Install JAVA
    command: |
      sudo apt-get update
      sudo apt-get install openjdk-8-jdk-headless -qq
  - name: Install conveyor
    init: curl -s https://static.conveyordata.com/cli-install/install.sh | bash
    command: |
      curl -s https://static.conveyordata.com/cli-install/update.sh | bash
  - name: Boot Airflow
    init: |
      gp sync-await pull
      gp sync-await aws
      docker-compose up airflow-init
  - name: Assume AWS role, set environment variables
    init: |
      gp idp login aws --role-arn arn:aws:iam::338791806049:role/seasonal-school-gitpod-role --duration-seconds 28800
      eval "$(aws configure export-credentials --format env)"
      gp sync-done aws

image:
  file: .gitpod.dockerfile
# VS Code settings
vscode:
  extensions:
    - ms-python.python
    - tamasfe.even-better-toml
    - ms-python.debugpy
    - ms-python.debugpy
    - charliermarsh.ruff

ports:
  - port: 5555
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
