[project]
name = "capstone-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "boto3>=1.36.9",
    "pyspark>=3.5.4",
    "requests>=2.32.3",
]
