[project]
name = "capstonellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "boto3>=1.36.9",
    "ipython>=8.32.0",
    "jupyter>=1.1.1",
    "pyspark>=3.5.4",
    "pytest>=8.3.4",
    "requests>=2.32.3",
]
